### ISSUE TITLE
Protolude re-exports Type with GHC 8.2 but not with GHC 8.0

### ISSUE THREAD

**Issue by jml** [sdiehl/protolude#79]
I have a library that uses Protolude and defines its own type called `Type`. I'd like it to compile with GHC 8.0 and 8.2 using protolude >= 0.2.1. 

If I import Protolude as

```haskell
import Protolude hiding (Type)
```

I get the following warning when using GHC 8.0 (actually stackage 9.21):

```
    [ 6 of 19] Compiling GraphQL.Internal.Syntax.AST ( src/GraphQL/Internal/Syntax/AST.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.2.0/build/GraphQL/Internal/Syntax/AST.o )

    /Users/jml/src/graphql-api/src/GraphQL/Internal/Syntax/AST.hs:49:1: warning: [-Wdodgy-imports]
        Module ‘Protolude’ does not export ‘Type’
```

If I import Protolude without hiding anything, I get the following error when using GHC 8.2 (actually stackage 10.4):

```
    [ 6 of 19] Compiling GraphQL.Internal.Syntax.AST ( src/GraphQL/Internal/Syntax/AST.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/GraphQL/Internal/Syntax/AST.o )

    /Users/jml/src/graphql-api/src/GraphQL/Internal/Syntax/AST.hs:81:55: error:
        Ambiguous occurrence ‘Type’
        It could refer to either ‘Protolude.Type’,
                                 imported from ‘Protolude’ at src/GraphQL/Internal/Syntax/AST.hs:49:1-16
                                 (and originally defined in ‘GHC.Types’)
                              or ‘GraphQL.Internal.Syntax.AST.Type’,
                                 defined at src/GraphQL/Internal/Syntax/AST.hs:172:1
       |
    81 | data VariableDefinition = VariableDefinition Variable Type (Maybe DefaultValue)
       |                                                       ^^^^
```

In both cases, protolude is constrained to >= 0.2.1.

I looked at the Protolude source to find where the re-export was coming from, but couldn't do so in the time allotted. In the meantime, I'll rename the type to work around this.

Is this actually a bug in Protolude?

**Comment by sdiehl** [comment]
Indeed, we can loosen the bound on exporting `Data.Kind` so it goes back to GHC 8.0.x which should fix your problem. Supporting anything before that would require some CPP because there isn't a shim we could put in place because `Data.Kind` is contingent on `-XTypeInType`.

**Comment by sdiehl** [comment]
Let me know if that fixes your issue.

**Comment by sdiehl** [comment]
Any follow up on this?

**Comment by jml** [comment]
Not yet. It's on my todo list.

**Comment by jml** [comment]
That fixed the issue, thanks!
